version: '3.7'

# Services
services:

  # Nginx Service
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    working_dir: /var/www/
    restart: unless-stopped
    volumes:
      - ./../:/var/www/
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:rw,delegated

  # Database Service
  database:
    image: mariadb
    restart: always
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: default
        MYSQL_ROOT_PASSWORD: root
    volumes:
       - mysqldata:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      # - ./mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "33006:3306"
      # Volumes

  # Redis Service
  redis:
    image: redis:6-alpine
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "toGwNuPX7HVe6fwI+W3y5znnupaQYBn3MwBZjO1q7Sg=" ]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # Scheduler Service
  scheduler:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./scheduler/config.ini:/etc/ofelia/config.ini
    depends_on:
      - php

volumes:

  mysqldata:

  redisdata:
